export const categories = [
  { id: 14, name: "Aléatoire", slug: "random" },
  { id: 1, name: "Belges", slug: "belges" },
  { id: 2, name: "Les perles 🤌", slug: "perles" },
  { id: 15, name: "Religion", slug: "religion" },
  { id: 3, name: "Attrape-nigauds", slug: "attrape+nigauds" },
  { id: 4, name: "Blonde", slug: "blonde" },
  { id: 5, name: "Politique", slug: "politique" },
  { id: 7, name: "Ta Mère", slug: "ta+mere" },
  { id: 8, name: "Ton Père", slug: "ton+pere" },
  { id: 9, name: "Toto", slug: "toto" },
  { id: 10, name: "Citations", slug: "citations" },
  { id: 11, name: "Devinettes", slug: "devinettes" },
  { id: 12, name: "Carambar", slug: "carambar" },
  { id: 13, name: "Lada", slug: "lada" },
];
